modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://modrinth.com/mod/minewordle"

[[mods]]
modId = "minewordle"
version = "${version}"
displayName = "MineWordle"
description = "Play Wordle inside Minecraft! Use /wordle command to open the game."
authors = "shunti"

[[dependencies.minewordle]]
    modId = "forge"
    type = "required"
    versionRange = "[36,)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.minewordle]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.16.5,1.17)"
    ordering = "NONE"
    side = "CLIENT"
